<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<!--<tr id="searchTable">
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
				<th><input type="text" class="form-control" placeholder="Buscar"/></th>
		</tr>-->
		<tr>
				<th>Referencia</th>
				<th>Moneda</th>
				<th>Cliente</th>
				<th title="Coordinador de operaciones">CO*</th>
				<th title="Ejecutivo de Compra y Logística">ECL*</th>
				<th title="Acesor en Comercio Exterior">ACE*</th>
				<th>Estatus</th>
				<th></th>
		</tr>
	</thead>
	<tfoot>
		<tr>
				<th class="col-md-2">Referencia</th>
				<th class="col-md-1">Moneda</th>
				<th class="col-md-2">Cliente</th>
				<th class="col-md-1">CO</th>
				<th class="col-md-1">ECL</th>
				<th class="col-md-1">ACE</th>
				<th class="col-md-1">Estatus</th>
				<th class="col-md-4 text-center"></th>
		</tr>
	</tfoot>
	<tbody>
		<?php if(isset($operaciones)):?>
			<?php foreach($operaciones as $operacion):?>
			<tr>
					<td nowrap><?php echo $operacion["id_u_referencia"] ?></td>
					<td nowrap><?php echo $operacion["n_espanol"] ?></td>
					<td nowrap><?php echo $operacion["nombre_marca"] ?></td>
					<td class="text-center">
						<span class="glyphicon glyphicon-user tooltip_info" data-toggle="tooltip" data-placement="left" title="<?php echo $operacion["co"] ?>"></span>
					</td> <!--CO-->
					<td class="text-center">
						<span class="glyphicon glyphicon-user tooltip_info" data-toggle="tooltip" data-placement="left" title="<?php echo $operacion["ecl"] ?>"></span>

					</td> <!--ACE-->
					<td class="text-center">
						<span class="glyphicon glyphicon-user tooltip_info" data-toggle="tooltip" data-placement="left" title="<?php echo $operacion["eta"] ?>"></span>


					</td>
					<td>
						<select class="form-control" id="est_<?php echo $operacion['id_u_referencia'];?>">
								<option value="x">Seleccione</option>
								<?php if(isset($estatus) && count($estatus)):?>
									<?php foreach ($estatus as $est): ?>
									<option value="<?php echo $est["id"];?>" <?php if(isset($operacion["status"])):?><?php if($operacion["status"]==$est["id"]):?>selected="selected"<?php endif;?><?php endif;?>><?php echo $est["estatus"]?></option>
										<?php if(isset($operacion["status"])):?><?php if($operacion["status"]==$est["id"]):?><?php echo $est["nombre"]?><?php endif;?><?php endif;?>

								<?php endforeach;?>
								<?php endif;?>
						</select>
					<td class="col-md-4 text-center">
						<div class="btn-group">
								<a type="button" class="btn btn-default"  href="<?php echo BASE_URL;?>/operaciones/perfil_referencia/<?php echo $operacion["id_u_referencia"];?>">
									<span class="glyphicon glyphicon-eye-open"></span>
								</a>
							<button type="button" class="btn btn-default" id="b-eliminar_{$dato.id_u_referencia}">
								<span class="glyphicon glyphicon-trash"></span>
							</button>
						</div>
					</td>
			</tr>
			<?php endforeach; ?>
		<?php endif;?>

	</tbody>
</table>

</div>
</div>
</div>
